edition = "2024";

package job_service.v1;

import "google/protobuf/empty.proto";

option go_package = "github.com/partiallyordered/int-backend-matt-1/gen/job_service";

// JobService provides methods for controlling a job worker service to run
// arbitrary Linux processes on the server machine.
service JobService {
  // CreateJob creates a job on the server.
  // We don't return a stream when creating a job because the API must include
  // a means of streaming after the fact anyway, therefore it's left up to the
  // client to manage the appearance of "instant-on" by making two requests.
  rpc CreateJob(CreateJobRequest) returns (google.protobuf.Empty);
  // StreamJobLog streams the job output. Only one output job output stream
  // (stdout or stderr) is streamed at a time. If the client requires, it can
  // stream the two separately. If the job stops, the stream will be closed by
  // the server.
  rpc StreamJobLog(StreamJobLogRequest) returns (stream StreamJobLogResponse);
  // SignalJob signals a job by sending it a client-specified signal. This
  // allows the client to stop a job in the manner it pleases, for example by
  // sending SIGINT, followed by SIGKILL after a timeout.
  rpc SignalJob(SignalJobRequest) returns (google.protobuf.Empty);
  // GetJobStatus returns the status of the job.
  rpc GetJobStatus(GetJobStatusRequest) returns (GetJobStatusResponse);
}

// CreateJobRequest is sent by the client when creating a job. The client
// should provide the job ID in order that if the request succeeds but the
// connection is lost the client can check the job status before creating a
// duplicate job.
message CreateJobRequest {
  // The job ID. This is client-created. The format is unspecified as clients
  // are not considered to be malicious, and this allows a client to use an
  // ergonomic ID such as "bob-finite-element-5" or "alice-build-run".
  string job_id = 1;
  // The executable to run as a job.
  string executable = 2;
  // The arguments that will be passed to the executable.
  repeated string args = 3;
}

// StreamJobLogRequest is sent by the client to begin streaming the output of
// the requested job. The client may stream either stdout or stderr.
message StreamJobLogRequest {
  // The job ID for which to stream the output.
  string job_id = 1;
}

// StreamJobLogResponse is sent by the server in response to a
// StreamJobLogRequest. Data is unmodified from the stdout or stderr output
// stream. This API does not specify a buffering strategy.
message StreamJobLogResponse {
  bytes output = 1;
}

// StopJobRequest is sent by the client to request a job be stopped.
message StopJobRequest {
  // The ID of the job to cancel.
  string job_id = 1;
}

// GetJobStatusRequest is sent by the client to request the status of a job.
message GetJobStatusRequest {
  // The job ID for which to request the job status.
  string job_id = 1;
}

// GetJobStatusResponse is sent by the server in response to a request for the
// job status.
message GetJobStatusResponse {
  // Indicates whether or not the job is completed.
  JobState job_state = 1;
  // The exit code will only be set if the job is finished. A zero exit code in
  // the case where the job is not finished is a default value, not successful
  // completion of the job.
  sint32 exit_code = 4;
}

// JobState indicates whether the job is running or has stopped.
enum JobState {
  JOB_STATE_UNSPECIFIED = 0;
  JOB_STATE_RUNNING = 1;
  JOB_STATE_STOPPED = 2;
}
